### ISSUE TITLE
cant use artisan command

### ISSUE THREAD

**Issue by karapho712** [ramonpego/laravel-sso#1]
![image](https://user-images.githubusercontent.com/66083311/89219816-11cb3f00-d603-11ea-9abb-ed05f9522de8.png)

Why i cant use the artisan command ?

**Comment by ramonpego** [comment]
Sorry about that, i has changed  command for
```php artisan broker:create```
```php artisan broker:delete```
```php artisan broker:list```

i'm so sorry, i'll change docs rigth now
