### ISSUE TITLE
Still stuck at login page after input data login in broker app

### ISSUE THREAD

**Issue by karapho712** [ramonpego/laravel-sso#2]
After i input email and password in login page, its still at login page. is it sso package works or i miss something ? 
i hope, if i login at broker(1) it will redirect to /home url like default auth laravel and if i go at broke(2) app at the same time. The login and register link will be invisible(hidden).

Sorry for bad english, I hope you understand what I'm explain about.

**Comment by ramonpego** [comment]
Hello, are you using SPA or something?

This package I got from https://github.com/zefy/laravel-sso that hasn't been updated in a long time.
I had the need to implement a single login on some systems in the company where I work.
But I ended up having to postpone, something didn't work on the server.

But the package uses the normal laravel login structure, but it authenticates on the website that you fill in the ENV
SSO_SERVER_URL =
it touches the indicated url logs it in and returns to the brooker where it redirects if so defined

I didn't have enough tests for the package, but i can try to help you if you continue to have problems

rlx with english i'm not good too

**Comment by karapho712** [comment]
its hard to explain in here, so i give video link to explain what i mean. This is the link https://youtu.be/HFgrIDLc6Bg
i hope we can find a solution about this

**Comment by karapho712** [comment]
By the way, I using laravel 7

**Comment by ramonpego** [comment]
I'll try it using laravel server (localhost: 8000) such as you
and follow up with feedback.
Its refreshing the page, so its reaching server indeed, but something occurs failing the login or login was successful and brooker doesn't recognize session

**Comment by karapho712** [comment]
the broker app reach the server and got error response when wrong email & password, but when use right email and password. The page is refresh but not recognized the session.

i looking at AuthenticatesUsers.php file now. I think the bug come from here

**Comment by ramonpego** [comment]
i'll look on package files and simulate your issue here but now i'm working, so i can't do right now.
But for me it's seems login occur but brooker not recognize

**Comment by karapho712** [comment]
Ah sorry to bother you, i really forget about timezone
Well, I'll wait for the good news
thanks beforee

**Comment by ramonpego** [comment]
See if anything here can help you
https://youtu.be/aq9A2hKiyDA
Really sorry about my english
